apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: rabbit-eventhub
    environment: tst
  name: rabbit-eventhub-tst-controller
spec:
  replicas: 1
  selector:
    app: rabbit-eventhub
    environment: tst
  template:
    metadata:
      labels:
        app: rabbit-eventhub
        environment: tst
    spec:
      containers:
      - image: rabbitmq:3-management 
        imagePullPolicy: IfNotPresent
        name: rabbit-eventhub-tst
        ports:
        - containerPort: 15672
          protocol: TCP
        - containerPort: 5672
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
