apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbit-eventhub
    environment: tst
  name: rabbit-external-tst
spec:
  ports:
  - port: 15672
    protocol: TCP
    name: api-port
  - port: 5672
    protocol: TCP
    name: data-port
  selector:
    app: rabbit-eventhub 
    environment: tst
  type: LoadBalancer
